### ISSUE TITLE
Windows build fails on intgemm 

### ISSUE THREAD

**Issue by ugermann** [browsermt/marian-dev#3]
For details see here: https://github.com/browsermt/marian-dev/runs/961679913.

**Comment by ugermann** [comment]
I wonder whether the github windows compile runs on an ARM processor.
https://docs.microsoft.com/en-us/cpp/cpp/m128i?view=vs-2019: "The __m128i data type is not supported on ARM processors."

**Comment by kpu** [comment]
intgemm is now working in `intgemm_reintegrated`
But some of @XapaJIaMnu 's wrapper code isn't working and I don't understand why there's duplicate code in https://github.com/marian-nmt/marian-dev/blob/intgemm_reintegrated/src/command/marian_conv.cpp#L64-L82

https://github.com/marian-nmt/marian-dev/pull/595/checks?check_run_id=962304985

**Comment by ugermann** [comment]
Looking at the code, I also have concerns about portability of the binary models, as they seem to depend on CPU architectures. Actually, I have three concerns here:
1. Models should be self-declaratory. In the worse case, by extension (e.g., .npz vs. .bin); ideally, however, by some magic number or line or range of bytes that Marian can check when loading. I want to be able to run marian-decoder with -m and -v only, without having to know what exactly is in model.bin.
2. Models should run everywhere. So if there's a CPU-architecture-dependent binary format, could the conversion happen at load time?
3. Device configuration should happen in Backend::ConfigureDevice(options). I don't like seeing device configuration details scattered all over the place. We already have that function in the master branch on browsermt/marian-dev. Truth be told, we should get rid of the public setInt...() functions to remove the temptation to fly-tip device configuration code in places where it doesn't belong.

**Comment by kpu** [comment]
As I have repeatedly tried to explain to you in https://github.com/marian-nmt/marian-dev/issues/693 the in-memory format depends on CPU which is why it's converted from row-major format at load time.

**Comment by ugermann** [comment]
So what's this about then in marian_conv?
```
  } else if(saveGemmTypeStr == "packed8avx2") { // packed8 for AVX2
    saveGemmType = Type::packed8avx2;
  } else if(saveGemmTypeStr == "packed8avx512") { // packed8 for AVX512
    saveGemmType = Type::packed8avx512;
```

**Comment by XapaJIaMnu** [comment]
@ugermann 

1) marian already recognises what is inside model.bin (it knows whether it's fbgemm or intgemm) . However, it still needs to be told whether to convert the output layer as an intgemm. I didn't know you can stick vocabulary in a.bin

**Comment by ugermann** [comment]
I don't think you can stick a vocab in a .bin. That's why I said -m **and** -v.

**Comment by XapaJIaMnu** [comment]
Our gemm types are intgemm8 and intgemm 16 are completely independent of the fbgemm types which are packed8avx2 and packed8avx512

**Comment by kpu** [comment]
Can we get back to fixing the dual use of the variable `graph` that's currently breaking MSVC and create a new issue if it doesn't relate to the windows build?

**Comment by XapaJIaMnu** [comment]
I will fix this tomorrow morning. I inadvertedly introduced this during one the merges with master.

**Comment by ugermann** [comment]
@XapaJIaMnu thanks for the explanation. I've updated the comments in the file to make that clear.

**Comment by kpu** [comment]
Works now

**Comment by ugermann** [comment]
On that note, @XapaJIaMnu please make sure you pull the changes I made to intgemm_interface.h into your intgemm "master" branch. Some compilers (e.g., whatever github uses for compilation on Windoze) don't like to expand #define'd macros with #ifdefs inside the macro argument.
