### ISSUE TITLE
Cmake requirements are incorrect. We now require 3.12.4

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/marian-dev#33]
https://github.com/browsermt/marian-dev/blob/0f0bcf99626c660227bb68b76267a8d2451e7172/CMakeLists.txt#L67

```
-- Submodule update
CMake Error at 3rd_party/marian-dev/CMakeLists.txt:67 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".
```
`add_compile_definitions` is only available in 3.12.4
@abhi-agg or @motin , not sure who changed it, as the commit got squashed. Is there an alternative to that, as it breaks compilation on ubuntu 16.04. At the very least we should update the requirements on the top:

https://github.com/browsermt/marian-dev/blob/0f0bcf99626c660227bb68b76267a8d2451e7172/CMakeLists.txt#L1

**Comment by abhi-agg** [comment]
@XapaJIaMnu I added the change through https://github.com/browsermt/marian-dev/pull/32 and https://github.com/browsermt/marian-dev/pull/24. Btw, where do you see these failures? I am asking because all CI checks were passing on these PRs before I merged them and CI already has an ubuntu 16.04 builder.

**Comment by XapaJIaMnu** [comment]
Ubuntu 16.04 by default includes a much older https://launchpad.net/ubuntu/xenial/+source/cmake I am not sure where the CI is pulling this from, but it's not from the official repos.

**Comment by abhi-agg** [comment]
@XapaJIaMnu I can update the `cmake_minimum_required` to 3.12.4. Where did you notice these failures btw?

**Comment by XapaJIaMnu** [comment]
On ubuntu 16.04 default installation.

**Comment by abhi-agg** [comment]
https://github.com/browsermt/marian-dev/pull/34 fixes this. So closing this.
