### ISSUE TITLE
What determines whether or not the output layer should be converted as an intgemm?

### ISSUE THREAD

**Issue by ugermann** [browsermt/marian-dev#4]
@XapaJIaMnu explained in #3:

> marian already recognises what is inside model.bin (it knows whether it's fbgemm or intgemm) . However, it still needs to be told whether to convert the output layer as an intgemm.

What determines whether or not the output layer should be converted as an intgemm?

**Comment by XapaJIaMnu** [comment]
I have described this in the wiki (look at the FAQ https://github.com/browsermt/coordination/wiki/Low-precision-GEMM-and-Intgemm , i need to update the outdated parameter names). Any command line switch `--gemm-precision int16/int8*` would tell the marian to perform the multiplication of the output layer of any model (fbgemm or intgemm or normal uncompressed model) with intgemm. Without that switch, BLAS will be used.
