### ISSUE TITLE
Native implementation of the wasm matrix multiply interface for Intel SSSE3

### ISSUE THREAD

**Issue by abhi-agg** [browsermt/marian-dev#51]
### Feature description
As per https://github.com/browsermt/bergamot-translator/issues/205, we would like to have an optimized implementation of the [generic matrix multiply interface](https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/wasm_intgemm_interface.h) for Intel SSSE3

cc @andrenatal @kpu @XapaJIaMnu

**Comment by kpu** [comment]
I remain confused as to the point of this exercise.  We had a working matrix multiply interface.  Every change is a tax on the working implementation.  Yet the justification for coming in to do a redesign is very limited and it's not clear what advantage the new interface has.  

Index to int32_t ok fine I get that, easy.  Why are we changing the order of arguments to functions?  

If you want a working version of your interface, wrap the existing calls.

**Comment by abhi-agg** [comment]
As per https://github.com/browsermt/marian-dev/pull/49#issuecomment-901829755 and https://github.com/browsermt/marian-dev/pull/49#issuecomment-902752109, I have clarified that the interface in https://github.com/browsermt/marian-dev/pull/49 is not a redesign of intgemm interface.

**Comment by abhi-agg** [comment]
We already have the native gemm implementation of this interface for intel with intgemm as the backend. So, closing this one.
