### ISSUE TITLE
Wrong use of parameters

### ISSUE THREAD

**Issue by XapaJIaMnu** [browsermt/marian-dev#62]
https://github.com/browsermt/marian-dev/blob/200e81c0cc88259c540b96afc6e0867cb05570b0/src/tensors/cpu/wasm_intgemm_fallback.cpp#L92

This looks wrong, Scale_A and Scale_B are already used to compute the unquantisation mutliplier? @kpu @abhi-agg  am I missing something? Spotted by @jerinphilip

**Comment by jerinphilip** [comment]
To be clear, this is probably a notational (or variable naming) confusion. `unquant_multiplier` as I understand is an optional scale applied to outputs post quantization.  `scale_A * scale_B` is `unquant_A*unquant_B`.

**Comment by kpu** [comment]
I think it's more of a naming issue.  In @abhi-agg 's concept you pass scale_A to prepareA where it is multiplied to quantize.  Then you pass the same scale_A to multiply and it is divided out.  In a sense scale_A is a property of A, which is pass to both methods.

**Comment by abhi-agg** [comment]
> In a sense scale_A is a property of A, which is passed to both methods.

This is right.

> `unquant_multiplier` as I understand is an optional scale applied to outputs post unquantization

I have [documented](https://github.com/browsermt/marian-dev/blob/master/src/tensors/cpu/wasm_intgemm_interface.h#L220-L221) it in the interface. However, if changing the name `unquant_multiplier` to something else could be helpful to make it more clear then it can be done as well. 👍🏾
