### ISSUE TITLE
Log about fallback multiply is causing performance issues

### ISSUE THREAD

**Issue by kpu** [browsermt/marian-dev#63]
This is causing excessive logging:

https://github.com/browsermt/marian-dev/blob/200e81c0cc88259c540b96afc6e0867cb05570b0/src/tensors/cpu/wasm_intgemm_fallback.cpp#L91

Let's reduce that to once at initialization.

**Comment by abhi-agg** [comment]
> This is causing excessive logging:
> 
> https://github.com/browsermt/marian-dev/blob/200e81c0cc88259c540b96afc6e0867cb05570b0/src/tensors/cpu/wasm_intgemm_fallback.cpp#L91
> 
> Let's reduce that to once at initialization.

I agree with you. This is what I am doing to resolve this:

1. I am removing all the logging from this file as all these functions will be called multiple times during inference and will/might impact the performance. Creating a PR for this.
2. As gemm module is linked at runtime for wasm target only, the decision whether an optimized or a fallback gemm implementation will run happens on JS side. So, I am logging this in JS artifacts (tracked in https://github.com/browsermt/bergamot-translator/issues/264). Creating a PR for this.

**Comment by kpu** [comment]
We could have JS explicitly signal the presence of the gemm intrinsic.  Or we could have C++ sense it.  

A dumb way to sense it is just to make the internal C function implementation incorrect.  So the C++ code will be able to tell if the intrinsic is intercepting (correct) or not (incorrect).  If incorrect, it just calls intgemm in the normal way without the C function.
