### ISSUE TITLE
Merge from marian-nmt/marian-dev

### ISSUE THREAD

**Issue by kpu** [browsermt/marian-dev#7]
There's a bunch of kludges like https://github.com/browsermt/mts/blob/master/3rd_party/CMakeLists.txt#L20-L22 that are fixed in marian-nmt/marian-dev

**Comment by kpu** [comment]
Ping @XapaJIaMnu @ugermann

**Comment by ugermann** [comment]
There are some merge conflicts that @XapaJIaMnu is better qualified to resolve than me.

**Comment by ugermann** [comment]
Ping @XapaJIaMnu. Before @motin spends much more time on trying to deal with protobuf, we should upgrade to the current version. I cannot merge marian-nmt/master because of merge conflicts that @XapaJIaMnu needs to resolve.

**Comment by XapaJIaMnu** [comment]
I did a merge about 10 days ago, that resolved all the merge conflicts. I did another merge today that resolved the conflicts that came due to the inclusion of @afaji 's code. This should've been a non issue.
